### ISSUE TITLE
PostgrexWal project Roadmap

### ISSUE THREAD

**Issue by json2008** [Byzanteam/postgrex_wal#32]
### Features:
Provides a broadway producer for building the postgesSQL WAL ingestion pipeline.

### Project module Description:
`PgSource `: Based on `Postgrex::ReplicationConnection` implementation, the wal event decoded by `pgoutput` is obtained and pushed to `PgProducer`.
`PgProducer`: A producer implementation based on Genstage.
Modules in the messages directory: Based on the pg replication protocol, the specific implementation of decoding various wal messages.。

### Currently implemented functionality
- [x] Establish pg_replication_connection to postgreSQL and get its logically decoded wal log (binary string)
- [x] Decode the original binary event into an Elixir struct.
- [x] Push to broadway producer (`PgProducer`)
- [x] You can integrate this `PgProducer` into your broadway pipeline as a pg wal ingestion pipleline.

### Possible additions in the future
- [ ]  pg_connect will be restarted when the consume rate continues to fall below the speed of the pg emit event and exceeds the buffer threshold. Not elegant enough. We need to implement a mechanism to pause replication.
- [ ] Currently only message formats up to protol 1,2 are supported. Support for new protocol formats may be added.

### Feedback is welcome!

**Comment by json2008** [comment]
@fahchen 

建议这个`issue`, 对项目，做一个整理。看，是否还有需要增减说明的？
